
package eprecise.efiscal4j.commons.domain.adress;

public enum Country {

                     AFEGANISTAO("132", "Afeganistão"),
                     ALBANIA("175", "República da Albania"),
                     ALEMANHA("230", "Alemanha"),
                     BURKINA_FASO("310", "Burkina Faso"),
                     ANDORRA("370", "Andorra"),
                     ANGOLA("400", "Angola"),
                     ANGUILLA("418", "Anguilla"),
                     ANTIGUA_E_BARBUDA("434", "Antiga e Barbuda"),
                     ANTILHAS_HOLANDESAS("477", "Antilhas Holandesas"),
                     ARABIA_SAUDITA("531", "Arábia Saudita"),
                     ARGELIA("590", "Argelia"),
                     ARGENTINA("639", "Argentina"),
                     ARMENIA("647", "República da Armenia"),
                     ARUBA("655", "Aruba"),
                     AUSTRALIA("698", "Australia"),
                     AUSTRIA("728", "Austria"),
                     AZERBAIJAO("736", "República do Azerbaijão"),
                     BAHAMAS("779", "Ilhas Bahamas"),
                     BAHREIN("809", "Ilhas Bahrein"),
                     BANGLADESH("817", "Bangladesh"),
                     BARBADOS("833", "Barbados"),
                     BELARUS("850", "República da Belarus"),
                     BELGICA("876", "Belgica"),
                     BELIZE("884", "Belize"),
                     BERMUDAS("906", "Bermudas"),
                     MIANMAR("930", "Mianmar (Birmania)"),
                     BOLIVIA("973", "Bolivia"),
                     BOSNIA_HERZEGOVINA("981", "República da Bosnia-Herzegovina"),
                     BOTSUANA("1015", "Botsuana"),
                     BRASIL("1058", "Brasil"),
                     BRUNEI("1082", "Brunei"),
                     BULGARIA("1112", "República da Bulgaria"),
                     BURUNDI("1155", "Burundi"),
                     BUTAO("1198", "Butão"),
                     CABO_VERDE("1279", "República de Cabo Verde"),
                     CAYMAN("1376", "Ilhas Cayman"),
                     CAMBOJA("1414", "Camboja"),
                     CAMAROES("1457", "Camarões"),
                     CANADA("1490", "Canadá"),
                     GUERNSEY("1504", "Ilha do Canal (Inclui Alderney e Sark)"),
                     JERSEY("1508", "Ilha do Canal Jersey"),
                     CANARIAS("1511", "Ilhas Canarias"),
                     CAZAQUISTAO("1538", "República do Cazaquistão"),
                     CATAR("1546", "Catar"),
                     CHILE("1589", "Chile"),
                     CHINA("1600", "República popular China"),
                     FORMOSA("1619", "Formosa (Taiwan)"),
                     CHIPRE("1635", "Chipre"),
                     COCOS("1651", "Ilhas Cocos (Keeling)"),
                     COLOMBIA("1694", "Colombia"),
                     COMORES("1732", "Ilhas Comores"),
                     CONGO("1775", "Congo"),
                     COOK("1830", "Ilhas Cook"),
                     COREIA_POP_DEM("1872", "República popular democrática Coreia"),
                     COREIA("1902", "República da Coreia"),
                     COSTA_DO_MARFIM("1937", "Costa do Marfim"),
                     CROACIA("1953", "República da Croacia"),
                     COSTA_RICA("1961", "Costa Rica"),
                     COVEITE("1988", "Coveite"),
                     CUBA("1996", "Cuba"),
                     BENIN("2291", "Benin"),
                     DINAMARCA("2321", "Dinamarca"),
                     DOMINICA("2356", "Ilha Dominica"),
                     EQUADOR("2399", "Equador"),
                     EGITO("2402", "Egito"),
                     ERITREIA("2437", "Eritreia"),
                     EMIRADOS_ARABES_UNIDOS("2445", "Emirados Árabes Unidos"),
                     ESPANHA("2453", "Espanha"),
                     ESLOVENIA("2461", "República da Eslovenia"),
                     ESLOVACA("2470", "República Eslovaca"),
                     ESTADOS_UNIDOS("2496", "Estados Unidos"),
                     ESTONIA("2518", "República da Estonia"),
                     ETIOPIA("2534", "Etiopia"),
                     FALKLAND("2550", "Falkland (Ilhas Malvinas)"),
                     FEROE("2593", "Ilhas Feroe"),
                     FILIPINAS("2674", "Filipinas"),
                     FINLANDIA("2712", "Finlandia"),
                     FRANCA("2755", "França"),
                     GABAO("2810", "Gabão"),
                     GAMBIA("2852", "Gambia"),
                     GANA("2895", "Gana"),
                     GEORGIA("2917", "República da Georgia"),
                     GIBRALTAR("2933", "Gibraltar"),
                     GRANADA("2976", "Granada"),
                     GRECIA("3018", "Grécia"),
                     GROENLANDIA("3050", "Groenlandia"),
                     GUADALUPE("3093", "Guadalupe"),
                     GUAM("3131", "Guam"),
                     GUATEMALA("3174", "Guatemala"),
                     GUIANA_FRANCESA("3255", "Guiana Francesa"),
                     GUINE("3298", "Guiné"),
                     GUINE_EQUATORIAL("3310", "Guiné Equatorial"),
                     GUINE_BISSAU("3344", "Guiné Bissau"),
                     GUIANA("3379", "Guiana"),
                     HAITI("3417", "Haiti"),
                     HONDURAS("3450", "Honduras"),
                     HONG_KONG("3514", "Hong Kong"),
                     HUNGRIA("3557", "República da Hungria"),
                     IEMEN("3573", "Iemen"),
                     MAN("3595", "Ilha de Man"),
                     INDIA("3611", "Índia"),
                     INDONESIA("3654", "Indonésia"),
                     IRAQUE("3697", "Iraque"),
                     IRA("3727", "República islâmica do Irâ"),
                     IRLANDA("3751", "Irlanda"),
                     ISLANDIA("3794", "Islandia"),
                     ISRAEL("3832", "Israel"),
                     ITALIA("3867", "Itália"),
                     JAMAICA("3913", "Jamaica"),
                     JOHNSTON("3964", "Ilhas Johnston"),
                     JAPAO("3999", "Japão"),
                     JORDANIA("4030", "Jordânia"),
                     KIRIBATI("4111", "Kiribati"),
                     LAOS("4200", "República popular democrática do Laos"),
                     LESOTO("4260", "Lesoto"),
                     LETONIA("4278", "República da Letónia"),
                     LIBANO("4316", "Libano"),
                     LIBERIA("4340", "Libéria"),
                     LIBIA("4383", "Líbia"),
                     LIECHTENSTEIN("4405", "Liechtenstein"),
                     LITUANIA("4421", "Lituânia"),
                     LUXEMBURGO("4456", "Luxemburgo"),
                     MACAU("4472", "Macau"),
                     MACEDONIA("4499", "Macedonia"),
                     MADAGASCAR("4502", "Madagascar"),
                     MADEIRA("4525", "Ilha da Madeira"),
                     MALASIA("4553", "Malásia"),
                     MALAVI("4588", "Malavi"),
                     MALDIVAS("4618", "Maldivas"),
                     MALI("4642", "Mali"),
                     MALTA("4677", "Malta"),
                     MARIANAS_DO_NORTE("4723", "Marianas do Norte"),
                     MARROCOS("4740", "Marrocos"),
                     MARSHALL("4766", "Ilhas Marshall"),
                     MARTINICA("4774", "Martinica"),
                     MAURICIO("4855", "Mauricio"),
                     MAURITANIA("4880", "Mauritania"),
                     MIDWAY("4901", "Ilhas Midway"),
                     MEXICO("4936", "México"),
                     MOLDAVIA("4944", "República da Moldavia"),
                     MONACO("4952", "Monaco"),
                     MONGOLIA("4979", "Mongólia"),
                     MONTENEGRO("4985", "Montenegro"),
                     MICRONESIA("4995", "Micronesia"),
                     MONTSERRAT("5010", "Ilhas Montserrat"),
                     MOCAMBIQUE("5053", "Moçambique"),
                     NAMIBIA("5070", "Namibia"),
                     NAURU("5088", "Nauru"),
                     CHRISTMAS("5118", "Ilha Christmas (Navidad)"),
                     NEPAL("5177", "Nepal"),
                     NICARAGUA("5215", "Nicaragua"),
                     NIGER("5258", "Niger"),
                     NIGERIA("5282", "Nigéria"),
                     NIUE("5312", "Niue"),
                     NORFOLK("5355", "Ilha Norfolk"),
                     NORUEGA("5380", "Noruega"),
                     NOVA_CALEDONIA("5428", "Nova Caledonia"),
                     PAPUA_NOVA_GUINE("5452", "Papua Nova Guiné"),
                     NOVA_ZELANDIA("5487", "Nova Zelândia"),
                     VANUATU("5517", "Vanuatu"),
                     OMA("5568", "Oma"),
                     PACIFICO("5665", "Ilhas do Pacífico (Possessão dos EUA)"),
                     PAISES_BAIXOS_HOLANDA("5738", "Países Baixos (Holanda)"),
                     PALAU("5754", "Palau"),
                     PAQUISTAO("5762", "Paquistão"),
                     PANAMA("5800", "Panamá"),
                     PARAGUAI("5860", "Paraguai"),
                     PERU("5894", "Peru"),
                     PITCAIRN("5932", "Ilha Pitcairn"),
                     POLINESIA_FRANCESA("5991", "Polinésia Francesa"),
                     POLONIA("6033", "República da Polônia"),
                     PORTUGAL("6076", "Portugal"),
                     PORTO_RICO("6114", "Porto Rico"),
                     QUENIA("6238", "Quénia"),
                     QUIRGUIZ("6254", "República Quirguiz"),
                     REINO_UNIDO("6289", "Reino Unido"),
                     REPUBLICA_CENTRO_AFRICANA("6408", "República Centro-Africana"),
                     REPUBLICA_DOMINICANA("6475", "República Dominicana"),
                     REUNIAO("6602", "Ilha Reunião"),
                     ZIMBABUE("6653", "Zimbaque"),
                     ROMENIA("6700", "Romênia"),
                     RUANDA("6750", "Ruanda"),
                     RUSSIA("6769", "Federação da Rússia"),
                     SALOMAO("6777", "Ilhas Salomão"),
                     SAINT_KITTS_E_NEVIS("6781", "Saint Kitts e Nevis"),
                     SAARA_OCIDENTAL("6858", "Saara Ocidental"),
                     EL_SALVADOR("6874", "El Salvador"),
                     SAMOA("6904", "Samoa"),
                     SAMOA_AMERICANA("6912", "Samoa Americana"),
                     SAO_CRISTOVAO_E_NEVES("6955", "Ilhas São Cristovão e Neves"),
                     SAN_MARINO("6971", "San Marino"),
                     SAO_PEDRO_E_MIQUELON("7005", "São Pedro e Miquelon"),
                     SAO_VICENTE_E_GRANADINAS("7056", "São Vicente e Granadinas"),
                     SANTA_HELENA("7102", "Santa Helena"),
                     SANTA_LUCIA("7153", "Santa Lúcia"),
                     SAO_TOME_E_PRINCIPE("7200", "Ilhas São Tomé e Príncipe"),
                     SENEGAL("7285", "Senegal"),
                     SEYCHELLES("7315", "Seychelles"),
                     SERRA_LEOA("7358", "Serra Leoa"),
                     SERVIA("7370", "Servia"),
                     CINGAPURA("7412", "Cingapura"),
                     SIRIA("7447", "República Árabe da Síria"),
                     SOMALIA("7480", "Somália"),
                     SRI_LANKA("7501", "Sri Lanka"),
                     SUAZILANDIA("7544", "Suazilandia"),
                     AFRICA_DO_SUL("7560", "Africa do Sul"),
                     SUDAO("7595", "Sudão"),
                     SUECIA("7641", "Suécia"),
                     SUICA("7676", "Suíça"),
                     SURINAME("7706", "Suriname"),
                     TADJIQUISTAO("7722", "República do Tadjiquistão"),
                     TAILANDIA("7765", "Tailândia"),
                     TANZANIA("7803", "República unida da Tanzânia"),
                     TERRITORIO_BRIT_OC_INDICO("7820", "Territorio Brit. Oc. Índico"),
                     DJIBUTI("7838", "Djibuti"),
                     CHADE("7889", "Chade"),
                     TCHECA("7919", "República Tcheca"),
                     TIMOR_LESTE("7951", "Timor Leste"),
                     TOGO("8001", "Togo"),
                     TOQUELAU("8052", "Ilhas Toquelau"),
                     TONGA("8109", "Tonga"),
                     TRINIDAD_E_TOBAGO("8150", "Trinidad e Tobago"),
                     TUNISIA("8206", "Tunísia"),
                     TURCAS_E_CAICOS("8230", "Ilhas Turcas e Caicos"),
                     TURCOMENISTAO("8249", "República do Turcomenistão"),
                     TURQUIA("8273", "Turquia"),
                     TUVALU("8281", "Tuvalu"),
                     UCRANIA("8311", "Ucrânia"),
                     UGANDA("8338", "Uganda"),
                     URUGUAI("8451", "Uruguai"),
                     UZBEQUISTAO("8478", "República do Uzbequistão"),
                     VATICANO("8486", "Est. da cidade do Vaticano"),
                     VENEZUELA("8508", "Venezuela"),
                     VIETNA("8583", "Vietna"),
                     VIRGENS_BRITANICAS("8630", "Ilhas Virgens (Britanicas)"),
                     VIRGENS_EUA("8664", "Ilhas Virgens (EUA)"),
                     FIJI("8702", "Fiji"),
                     WAKE("8737", "Ilha Wake"),
                     CONGO_REP_DEM("8885", "República democrática do Congo"),
                     ZAMBIA("8907", "Zâmbia"),
                     ZONA_DO_CANAL_DO_PANAMA("8958", "Zona do Canal do Panamá"),
                     PROVISAO_DE_NAVIOS_E_AERONAVES("9903", "Provisão de Navis e Aeronaves"),
                     A_DESIGNAR("9946", "A designar"),
                     BANCOS_CENTRAIS("9950", "Bancos Centrais"),
                     ORGANIZACOES_INTERNACIONAIS("9970", "Organizações Internacionais");

    private String value;

    private String description;

    private Country(final String value, final String description) {
        this.value = value;
        this.description = description;
    }

    public String getValueWithDescription() {
        return this.value + " - " + this.description;
    }

    public String getValue() {
        return this.value;
    }

    public String getDescription() {
        return this.description;
    }

    public static Country findByCode(final String code) {
        for (final Country entity : Country.values()) {
            if (entity.getValue().equals(code)) {
                return entity;
            }
        }
        return null;
    }

    @Override
    public String toString() {
        return this.getDescription();
    }

}
